name: Build ZMK Firmware

on:
  push:
    branches:
      - main-jp
      - main-us
    paths:
      - 'config/**'
  pull_request:
    branches:
      - main-jp
      - main-us
    paths:
      - 'config/**'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
